### ISSUE TITLE
Up-to-date message incorrectly states that I'm not using the latest version (2.2.6)

### ISSUE THREAD

**Issue by nicolasjoly** [Kissaki/MumPI#51]
If I go on MYSERVER/MumPI/admin/?page=login, it says at the bottom: "The recent version of MumPI is 2.2.3", instead of the usual up-to-date message.

**Comment by Kissaki** [comment]
Thank you for the feedback.

As for 1.: Order is not alphabetical primarily, but the position value of the channel takes precedence.
What is the order if you connect via Mumble client? And what are the position values of the two channels?

**Comment by Kissaki** [comment]
As for 2., that is still hosted on sourceforge, which my setup connection does not work with, and I can not visit any HTTPS SF page right now …
I really have to move that away from SF…

**Comment by Kissaki** [comment]
2. should be fixed

If you could create separate issue tickets next time so they can be tracked individually!?

**Comment by nicolasjoly** [comment]
You are right, it is completely impossible to understand/follow what is going on :) So I made 3 separate issues.

**Comment by Kissaki** [comment]
Is this fixed for you?

**Comment by nicolasjoly** [comment]
Yes it is :)

**Comment by Kissaki** [comment]
I does not load for me, I guess because of different origin of script or sth - maybe an addon I use.
I will have to check on that separately.
But this issue is fixed then.
