### ISSUE TITLE
ChannelViewer doesn't put the mumble links since 2.2.6

### ISSUE THREAD

**Issue by nicolasjoly** [Kissaki/MumPI#53]
I had to revert back one line in ChannelViewerProtocolProducer.php so the links would work again. The commented line is the new one and the one above it is the old one.

```
$connecturlTemplate = 'mumble://MYIP:64738' . urlencode(SettingsManager::getInstance()->getServerAddress($server->getId())) . '%s?version=1.2.8';
//$connecturlTemplate = $serverConnectAddress != null ? 'mumble://%s?version=1.2.0' : null;
```

**Comment by Kissaki** [comment]
I noticed they do not work for me, but thought it was because of some special characters.
I guess I will have to look into this again.

The links worked for you with the previous version?

**Comment by nicolasjoly** [comment]
Yes and by changing "connecturlTemplate" back to it's original values (getting the line from 2.2.5 and putting it in 2.2.6), it works again.

**Comment by Kissaki** [comment]
$connecturlTemplate = 'mumble://MYIP:64738' . urlencode(SettingsManager::getInstance()->getServerAddress($server->getId())) . '%s?version=1.2.8';

does not really make sense though.

That will produce an URL with IP and port, but the port is not a valid port.
It does not produce valid urls for me at all.

I guess you do not have `$viewer_serverAddresses` configured for the server?

The version as it is works for me with trivial alphanumeric channel names.
Ones with a space do not work currently.
But I can not see the issue or solution you describe.

**Comment by nicolasjoly** [comment]
With my change, the URL seems fine. I can click it and it will connect to my server no problem. Here's what it looks like in your JSON that I'm using:

"x_connecturl":"mumble:\/\/111.111.111.111:64738?version=1.2.12"

**Comment by Kissaki** [comment]
Do you have `$viewer_serverAddresses` configured in `settings.inc.php`?

**Comment by Kissaki** [comment]
Close as no further input/response. Works for me, unreproducible, implausible fix description.

**Comment by Kissaki** [comment]
The mentioned space character issue is/was tracked in #56.
