### ISSUE TITLE
Server Error 500 

### ISSUE THREAD

**Issue by 1ijack** [Kissaki/MumPI#55]
This is not an issue, but a solution that should be added into the FAQ
after the installation and configuration, if you're seeing the `Server Error 500` page:
```
The website encountered an error while retrieving http://<url>/user/index.php. It may be down for maintenance or configured incorrectly
```

Do the following:
h2. Server Error 500 or Blank Page after MumPI Install
Do the following:
1. Add the Murmur.php (that's generated by Murmur.ice - located in /usr/share/slice/Murmur.ice) which is provided by the murmur server into the `<MumPI>/classes` directory.
2. Change the `$iceGeneratedMurmurPHPFileName` variable in the `settings.inc.php` to the same filename that you added into the `<MumPI>/classes` directory. Example: `$iceGeneratedMurmurPHPFileName = 'Murmur.php';`

**Comment by Kissaki** [comment]
500 can have different sources.

I added a point about 500 to the FAQ https://github.com/Kissaki/MumPI/wiki/FAQ#when-opening-mumpi-i-receive-a-500-server-error-page

As for self-generating, the FAQ entry states that you 1. generate it and then 2. set the setting, so I think that should be sufficient
