### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by PureLoneWolf** [Kissaki/MumPI#58]
I have just installed MumPi on my server and, whilst MumPi is working perfectly, I can't seem to use JSON.  Every time I try various status tools to test, I get either a malformed response or invalid response error messages.

I have it set up under http://mydomain.com/mumble/viewer2/ 

Could someone give an example URL that I would use in, say, http://www.mumble.com/mumble-server-status.php?

Server is 1.2.8 running on Debian Jessie.

Many thanks in advance for any help

**Comment by PureLoneWolf** [comment]
Ok, so I tried http://mydomain.com/mumble/?view=json&serverId=1 and I am now getting the following error:

Invalid JSON: Invalid JSON, missing : x_connecturl

Cheers

**Comment by Kissaki** [comment]
`https://example.org/?view=json&serverId=1` for pure JSON,
`https://example.org/?view=json&serverId=1&callback=?` for JSONP

`x_connecturl` is optional as per [CVP protocol specification](http://wiki.mumble.info/wiki/Channel_Viewer_Protocol)
So if your consumer *requires* that, it does not follow the CVP specification.

Recent MumPI version do provide `x_connecturl? .
Which version are you using then?
Did you set `$viewer_serverAddresses` in the settings?

**Comment by PureLoneWolf** [comment]
I think I found the issue.  I just saw in the settings file that you need to call the URL from where the settings file is.  For me that is http://www.example.com/mumble/?view=json&serverId=1

Now it seems to be working :D
