### ISSUE TITLE
Ubuntu 16.04: missing php-zeroc-ice and PHP7

### ISSUE THREAD

**Issue by MartNytrm** [Kissaki/MumPI#60]
Hi there,

I was migrating my Mumble server to Ubuntu 16.04 and planed to use again MumPI for little administration and providing CVP. 
While preparing PHP/Apache for Ice I realized that the package "php-zeroc-ice" is not available in the Xenial repositories and so I am not able to get the "IcePHP.so". 
The status of "php-zeroc-ice" in Xenial is "Superseded" (https://launchpad.net/ubuntu/xenial/amd64/php-zeroc-ice/3.5.1-6ubuntu2).
The reason for the missing "php-zeroc-ice" seems to be clearly 16.04 shipping with PHP7 (https://bugs.launchpad.net/ubuntu/+source/zeroc-ice/+bug/1566572) and even ZeroC's latest version 3.6.2 seems only to be compatible with PHP5.6 (https://doc.zeroc.com/display/Ice36/Supported+Platforms+for+Ice+3.6.2#SupportedPlatformsforIce3.6.2-IceforPHP). 
But I there is hope for 3.7 (https://github.com/zeroc-ice/ice/blob/master/CHANGELOG-3.7.md).

Is there at this time a way to get Ice and PHP or better Mumble server, Ice and MumPI to work on Ubuntu 16.04 which I haven't found? Or do we have to be patient?
Thanks!

Greets
Nytrm

**Comment by Kissaki** [comment]
Sorry, I am/was not aware of any such issues, or about future packaging plans by Ubuntu in this regard, or any potential solutions. If Ice is not compatible with PHP7, maybe an older PHP can be installed via packages with Ice, or maybe someone else provides an adequate package repository. Other than that, self-compile of older versions would be possible…

**Comment by MartNytrm** [comment]
Thanks for the answer! That's what i thought. As a downgrade to PHP5 is no option for me because of other applications, I will wait for zeroc-ice 3.7 and its promising compatibility with PHP7.
Thanks! (Thanks for your work, too, by the way!)
