### ISSUE TITLE
PHP Fatal Error with bleeding edge config

### ISSUE THREAD

**Issue by Ashaman-** [Kissaki/MumPI#62]
Running on Arch Linux.
PHP 5.6.24
Apache 2.4.23
zeroc-ice-php56 3.6.2-1

Error log http://pastebin.com/5E00hRzv

Any suggestions for how to make it work, or should I just give up and use debian instead?

**Comment by Kissaki** [comment]
With non-default/expected php-zeroc-ice you will have to generate your own `Murmur.php` from `Murmur.ice`.
See https://github.com/Kissaki/MumPI/wiki/FAQ#how-to-generate-a-murmurphp-file-from-the-murmurice-slice-file

**Comment by Ashaman-** [comment]
Yes, thank you!
I actually tried that before, but it appears I did not follow the directions closely enough.
