### ISSUE TITLE
Installationsanleitung

### ISSUE THREAD

**Issue by Headcrach** [Kissaki/MumPI#63]
Moin,

gibt es auch eine etwas ausführlichere und aktuellere Installationsanleitung?

Danke für die Informationen im voraus.

Gruß

**Comment by dceonline** [comment]
Also check out the FAQ https://github.com/Kissaki/MumPI/wiki/FAQ!

Regards

Ortwin

**Comment by Headcrasch** [comment]
Moin,

danke für die Links. Aber leider geben die mir nicht die Informationen die ich brauche.
Was muss installiert werden?
Ein LAMP oder brauch ich nur php?
Wäre schön wenn man sich etwas genauer  ausdrückt.
Danke schonmal im voraus.
Gruß

**Comment by Kissaki** [comment]
Grundkenntnisse in Administration sind vorausgesetzt bzw. müssen separat angelesen werden, da man es ja hosten möchte.

Wenn du es über einen Webserver hosten möchtest, dann brauchst du einen Webserver.
Wenn du es über ein anderes Kommunikationsmittel verfügbar machen möchtest kannst du auch etwas anderes verwenden.

MumPI selbst nutzt PHP mit der ZeroC Ice Erweiterung. Das ist notwendig für die HTML und Datengenerierung.

Ob du nun LAMP verwendest oder etwas anderes, oder es manuell zusammenbaust macht keinen Unterschied (für MumPI).

Da du nicht beschrieben hast was du eigentlich machen möchtest, und auch nicht was du probiert hast und was nicht funktioniert *rate ich einfach mal*:
**Ja, du brauchst LAMP, installierst für PHP noch die ZeroC Ice Erweiterung, und folgst dann weiter der Anleitung (entpackst es einfach, rufst es auf, und loggst dich einmal im Adminbereich ein, was automatisch diesen Account erstellt).**

Die Installationsanleitung für MumPI kann nicht jede erdenkliche Setup von umgebender Software auflisten oder erklären.
Ein Beispiel mit LAMP oder Nginx wäre natürlich möglich und für Neulinge vielleicht hilfreich.

**Comment by Headcrasch** [comment]
Moin,
sorry das meine Frage vielleicht doch etwas zu dünn war.
Also ich habe vorher das MumbleAdminPlugin genutzt. Leider würde die Entwicklung für das Tool eingestellt. Daraufhin hat mich der Entwickler dieses Tool angesproch das ich sein doch bitte nutzen soll.

Nun zudem was ich habe und nutzen möchte. 
Ich habe ein PC mit Ubuntu 14.04 LTS wobei ich auf Debian umsteigen werde, das weiß ich nicht. 
Bevor ich zu viel installieren wollte ich vorfragen was ich brauche. Ich gehe immer dem Spruch nach " soviel wie möglich soviel wie nötig".

Ich werde dann mal am Wochenende den LAMP mit PHP und ZeroC Ice. Um mir dann mal das Tool anzuschauen.

Trotzdem Danke für die Ausführliche Aussage. Sie hat mir weiter geholfen.

Gruß
