### ISSUE TITLE
does not work on Ice 3.6.x

### ISSUE THREAD

**Issue by sss123next** [Kissaki/MumPI#69]

**Comment by Kissaki** [comment]
Last time I tried, ZeroC did not provide recent Ice packages for recent PHP versions for Ubuntu Server LTS.
As a result, I was unable to test and make it work.
Looking at their download page it looks like that may have changed; it looks like they do provide packages.

**Comment by sss123next** [comment]
any news ?

**Comment by Kissaki** [comment]
Tried/Started setting up a test environment with docker in the branch https://github.com/Kissaki/MumPI/tree/docker-testenv
No conclusion/result yet

**Comment by tchncs** [comment]
@Kissaki i found the files in `/usr/share/php` for debian 9.6 - this issue provides no description so i don't know if i have the same issues:

mumpi/classes/Murmur_1.2.4.php : line 1188 exception

**Comment by sss123next** [comment]
this is unrelated, you just need to regenerate murmur.php via ice

**Comment by kripton** [comment]
I've tried setting up MumPi on my Gentoo server using Ice 3.6.3 and PHP 7.0.25. According to phpinfo(), the Ice extension is loaded correctly. I've also generated the Murmur_1.2.17.php file using the slice2php tool and adapted the settings file accordingly. However, I do get a PHP error:

> <b>Fatal error</b>:  Uncaught InvalidArgumentException: unexpected argument type object in /var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php:108
Stack trace:
#0 /var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php(108): Ice_initialize(Object(Ice_InitializationData))
#1 /var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php(68): ServerInterface_ice-&gt;initIce34()
#2 /var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php(41) : eval()'d code(1): ServerInterface_ice-&gt;__construct()
#3 /var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php(41): eval()
#4 /var/www/localhost/vhost/domain/mumpi/admin/index.php(28): ServerInterface::getInstance()
#5 {main}
  thrown in <b>/var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php</b> on line <b>108</b><br />

Anything I can do to help debugging this issue?

**Comment by Kissaki** [comment]
Hey, sorry, I'm not at home, so I can't check for sure, but you're probably also using a newer version of the ice php extension, which probably has different usage syntax, hence the error in serverinterface.php.
If you could post the php ice extension version, that could be verified later/by someone else. 

On 23 December 2017 22:46:06 CET, kripton <notifications@github.com> wrote:
>I've tried setting up MumPi on my Gentoo server using Ice 3.6.3 and PHP
>7.0.25. According to phpinfo(), the Ice extension is loaded correctly.
>I've also generated the Murmur_1.2.17.php file using the slice2php tool
>and adapted the settings file accordingly. However, I do get a PHP
>error:
>
>> <b>Fatal error</b>:  Uncaught InvalidArgumentException: unexpected
>argument type object in
>/var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php:108
>Stack trace:
>#0
>/var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php(108):
>Ice_initialize(Object(Ice_InitializationData))
>#1
>/var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php(68):
>ServerInterface_ice-&gt;initIce34()
>#2
>/var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php(41) :
>eval()'d code(1): ServerInterface_ice-&gt;__construct()
>#3
>/var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php(41):
>eval()
>#4 /var/www/localhost/vhost/domain/mumpi/admin/index.php(28):
>ServerInterface::getInstance()
>#5 {main}
>thrown in
><b>/var/www/localhost/vhost/domain/mumpi/classes/ServerInterface.php</b>
>on line <b>108</b><br />
>
>Anything I can do to help debugging this issue?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kissaki/MumPI/issues/69#issuecomment-353749961

Sent from mobile. Please excuse my brevity.

**Comment by lamiricore** [comment]
I'm trying to install mumpi on a debian buster with php 7.3.19 and ice 3.7.2. 

When i try to run it i have this php error : 

`Fatal error: Uncaught Error: Call to undefined function Ice_loadProfile() in /usr/share/nginx/html/mumpi/classes/ServerInterface.php:84 Stack trace: #0 /usr/share/nginx/html/mumpi/classes/ServerInterface.php(66): ServerInterface_ice->initIce33() #1 /usr/share/nginx/html/mumpi/classes/ServerInterface.php(41) : eval()'d code(1): ServerInterface_ice->__construct() #2 /usr/share/nginx/html/mumpi/classes/ServerInterface.php(41): eval() #3 /usr/share/nginx/html/mumpi/viewer/index.php(27): ServerInterface::getInstance() #4 {main} thrown in /usr/share/nginx/html/mumpi/classes/ServerInterface.php on line 84`

So i think this is the same probleme that described above and i know this project is not actively maintened but in case someone succeed to install it recently...

**Comment by AtomicHaggis** [comment]
I have forked the repo and am actively working to get this running with Ubuntu 20.04 and Ice 3.7.  I will also update it for Ubuntu 22.04 once that is released, assuming I can actually get it working.

**Comment by Kissaki** [comment]
If you argue and document removal of no longer supported versions in the MR, removing them is not a problem, it will be appreciated.

Yes, I can and will merge after review and reasonable confirmation that it works.

**Comment by AtomicHaggis** [comment]
I see that this has been merged and is now part of the latest released version, so this issue could be closed now?

**Comment by sss123next** [comment]
i am not using this functionality anymore, so can't test it right now, my old setup just works already many years ), no need to make any changes in vservers

**Comment by Kissaki** [comment]
Yes, it was PR #74
