### ISSUE TITLE
Installation problem.

### ISSUE THREAD

**Issue by andrewschott** [Kissaki/MumPI#70]
I am working on getting MumPi installed and got thru the /mumpi/install portion ok

~~~
settings.inc.php seems to be in place. Skipping…

admins.dat does not have to be converted.
You’re done.
You may now want to further configure your server(s) and the interface in the admin section,
or go straight to the user section.
~~~

But then when I click on either admin or user link provided, I get the following:

~~~
Template file not found when trying to parse template: HTMLHead
Template file not found when trying to parse template: header
Template file not found when trying to parse template: login
Template file not found when trying to parse template: footer
~~~

Any tips on what I jacked up?
Thanks!

**Comment by Kissaki** [comment]
Hey,

in your settings.inc.php what [theme](https://github.com/Kissaki/MumPI/blob/c24110434afe6de142534a4496ffa8b9deb3787d/settings.inc.default.php#L23) do you have configured?
If it can't find the template files in the corresponding theme folder [it throws this error](https://github.com/Kissaki/MumPI/blob/c24110434afe6de142534a4496ffa8b9deb3787d/classes/TemplateManager.php#L16).

**Comment by andrewschott** [comment]
Sorry for the late reply, been busy with work.

As for the theme, I left it at 'default'.

**Comment by Kissaki** [comment]
```$ theme           = 'default';```
Is that missing a PHP variable `$` dollar sign? That's from the terminal, right?

**Comment by andrewschott** [comment]
Yeah it is from the cli.  

The $ is there.  here is the region of the file raw:

// currently available: en, de ; en is recommended
$defaultLanguage = 'en';
// only "default" right now
$theme           = 'default';

**Comment by Kissaki** [comment]
Next I would try setting debug to true `$debug = true;` in the settings file. This should make PHP report/log all (errorreporting E_ALL). Then check your webserver/php log for errors or warnings. Or if you have display errors enabled they may also be displayed inline on the page.

When you access /admin/ you can see it should parse template files from the theme; [HTMLHead](https://github.com/Kissaki/MumPI/blob/master/admin/index.php#L61), header, meta and footer. Files with these names should exist in the {theme folder](https://github.com/Kissaki/MumPI/tree/master/themes/admin/default).

If all of this is in place, maybe the php runtime can't resolve or access these files?

**Comment by andrewschott** [comment]
OK thanks, I will try that, and report back.

Appreciate the help sofar.
